### ISSUE TITLE
[Auth] OAuth 2.0 쓸거임?

### ISSUE THREAD

**Issue by PngWnA** [PngWnA/kuaaa.net#4]
> OAuth2.0 = 소셜로그인
그
* 네이버로 로그인
* 구글로 로그인
이런 기능들

**Comment by susemeee** [comment]
있으면 좋긴 한데 높은 우선순위는 아닌듯

**Comment by PngWnA** [comment]
다른분 생각은 어떠심
@jun2077681 @kij787 @Yerim0718

**Comment by PngWnA** [comment]
일단 기본 로그인 구현하고 추가로 하는걸로.
